#!/bin/bash
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║   AlterLab FC Skills — Installation Guide    ║"
echo "  ║   36 Claude AI Skills for Communication      ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
echo "  Departments:"
echo "    PRA — Public Relations & Advertising (12 skills)"
echo "    CDM — Cinema & Digital Media (12 skills)"
echo "    NMC — New Media & Communication (12 skills)"
echo ""
echo "  ──────────────────────────────────────────────"
echo "  Skills found:"
find skills -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' '
echo ""
echo "  Usage with Claude Code CLI:"
echo "    cd $(pwd)"
echo "    claude \"act as my screenwriter assistant\""
echo ""
echo "  Usage with Claude Projects:"
echo "    Upload SKILL.md files from skills/{dept}/ to your project"
echo ""
echo "  ──────────────────────────────────────────────"
echo "  Built by AlterLab Creative Technologies Laboratory"
echo ""
